#!/bin/bash


ip link set dev eth0 up # FAI
ip addr add 6.6.7.130/27 dev eth0

ip link set dev eth1 up # B1_Client0
ip addr add 192.168.255.1/25 dev eth1

# echo 1 > /proc/sys/net/ipv4/ip_forward
# ip route add 6.6.7.40/29 via 6.6.7.129 # réseau avec WebServer via FAI
# ip route add 6.6.7.82/29 via 6.6.7.129 # réseau avec DNS_Server via FAI
