#!/bin/bash

ip link set dev eth0 up # switch avec R1 et R2
ip addr add 6.6.7.1/24 dev eth0

ip link set dev eth1 up # Box0
ip addr add 6.6.7.97/27 dev eth1

ip link set dev eth2 up # Box1
ip addr add 6.6.7.129/27 dev eth2

echo 1 > /proc/sys/net/ipv4/ip_forward

# ip route add 6.6.7.96/27 via 6.6.7.1 # réseau avec Box0 via FAI
# ip route add 6.6.7.128/27 via 6.6.7.1 # réseau avec Box1 via FAI

systemctl start quagga

(   echo "zebra";
    echo "en";
    echo "conf t";
    echo "router rip";
    echo "network 6.6.7.96/29"; # Box0
    echo "network 6.6.7.128/29"; # Box1
    echo "network 6.6.7.0/24"; # R1 R2
    echo "exit";
    echo "exit";
    echo "write mem";
    echo "exit"
) | telnet localhost ripd
