#!/bin/bash

ip link set dev eth0 up # switch avec FAI et R2
ip addr add 6.6.7.2/24 dev eth0

ip link set dev eth1 up # R_Services
ip addr add 6.6.7.33/27 dev eth1



echo 1 > /proc/sys/net/ipv4/ip_forward

ip route add 6.6.7.40/29 via 6.6.7.34 # réseau avec WebServer via R_Service


