#!/bin/bash

ip link set dev eth0 up # switch avec FAI et R2
ip addr add 6.6.7.2/24 dev eth0

ip link set dev eth1 up # R_Services
ip addr add 6.6.7.33/27 dev eth1



echo 1 > /proc/sys/net/ipv4/ip_forward

# ip route add 6.6.7.40/29 via 6.6.7.34 # réseau avec WebServer via R_Service
# ip route add 6.6.7.80/29 via 6.6.7.3 # réseau avec DNS_Server via R2

# # ----------- BOX
# ip route add 6.6.7.96/27 via 6.6.7.1 # réseau avec Box0 via FAI
# ip route add 6.6.7.128/27 via 6.6.7.1 # réseau avec Box1 via FAI

systemctl start quagga

(   echo "zebra";
    echo "en";
    echo "conf t";
    echo "router rip";
    echo "network 6.6.7.32/27"; # R_Service
    echo "network 6.6.7.0/24"; # FAI, R2
    echo "exit";
    echo "exit";
    #echo "write mem";
    #echo "exit"
) | telnet localhost ripd
