#!/bin/bash

ip link set dev eth0 up # R2
ip addr add 6.6.7.66/27 dev eth0

ip link set dev eth1 up # DNS_Server
ip addr add 6.6.7.81/29 dev eth1

ip link set dev eth2 up # R_Services
ip addr add 6.6.7.18/28 dev eth2


echo 1 > /proc/sys/net/ipv4/ip_forward
ip route add 6.6.7.40/29 via 6.6.7.65 # réseau avec WebServer via R2
