#!/bin/bash

ip link set dev eth0 up # R1
ip addr add 6.6.7.34/27 dev eth0

ip link set dev eth1 up # WebServer0
ip addr add 6.6.7.41/29 dev eth1


ip link set dev eth2 up # R_Net_Services
ip addr add 6.6.7.17/28 dev eth2


echo 1 > /proc/sys/net/ipv4/ip_forward
