#!/bin/bash

ip link set dev eth0 up # R1
ip addr add 6.6.7.34/27 dev eth0

ip link set dev eth1 up # WebServer0
ip addr add 6.6.7.41/29 dev eth1


ip link set dev eth2 up # R_Net_Services
ip addr add 6.6.7.17/28 dev eth2


echo 1 > /proc/sys/net/ipv4/ip_forward
ip route add 6.6.7.80/29 via 6.6.7.33 # réseau avec DNS_Server via R1

# ----------- BOX
ip route add 6.6.7.96/27 via 6.6.7.33 # réseau avec Box0 via R1
ip route add 6.6.7.128/27 via 6.6.7.33 # réseau avec Box1 via R1